run:
  timeout: 5m

linters:
  enable:
    - asciicheck
    - bidichk
    - errorlint
    - gocritic
    # - gofmt # we are using gofumpt instead
    - gofumpt
    - goimports
    - makezero
    - misspell
    - nolintlint
    - perfsprint
    - prealloc
    - testifylint
    - unconvert
    - usestdlibvars
    - wastedassign
    - wrapcheck

linters-settings:
  goimports:
    # A comma-separated list of prefixes, which, if set, checks import paths
    # with the given prefixes are grouped after 3rd-party packages.
    # Default: ""
    local-prefixes: "github.com/inexio/go-monitoringplugin"

  nolintlint:
    # Enable to require an explanation of nonzero length after each nolint directive.
    # Default: false
    require-explanation: true
    # Enable to require nolint directives to mention the specific linter being suppressed.
    # Default: false
    require-specific: true

  revive:
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#receiver-naming
      - name: receiver-naming
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - wrapcheck
